mode: post-hoc
#post-hoc, real-time
alg: HTM
#HTM, SteeringEntropy, IForest, OCSVM, KNN
#LightGBMModel, NBEATSModel, TCNModel, TransformerModel, RNNModel, ARIMA

do_gridsearch: false
learn_in_testing: false

preprocess:
  difference: false
  standardize: false
  movingaverage: false

windows_ascore:
  recent: 7
  previous: 21
  change_detection: 21
  change_thresh_percent: 30

subjects_testfiles_wltogglepoints:
  zaychik:
    test1-L1.xls:
      time_total: 60
      times_wltoggle:
        - 20
        - 45
    test2-L1.xls:
      time_total: 100
      times_wltoggle:
        - 35
        - 65
  rian:
    test1-L1.xls:
      time_total: 60
      times_wltoggle:
        - 20
        - 45
    test2-L1.xls:
      time_total: 100
      times_wltoggle:
        - 35
        - 65
  miller:
    test1-L1.xls:
      time_total: 60
      times_wltoggle:
        - 20
        - 45
    test2-L1.xls:
      time_total: 100
      times_wltoggle:
        - 35
        - 65
  jeremy:
    test1-L1.xls:
      time_total: 60
      times_wltoggle:
        - 20
        - 45
    test2-L1.xls:
      time_total: 100
      times_wltoggle:
        - 35
        - 65
  jacob:
    test1-L1.xls:
      time_total: 60
      times_wltoggle:
        - 20
        - 45
    test2-L1.xls:
      time_total: 100
      times_wltoggle:
        - 35
        - 65
  mike:
    test1-L1.xls:
      time_total: 60
      times_wltoggle:
        - 20
        - 45
    test2-L1.xls:
      time_total: 100
      times_wltoggle:
        - 35
        - 65
  hiroki:
    test1-L1.xls:
      time_total: 60
      times_wltoggle:
        - 20
        - 45
    test2-L1.xls:
      time_total: 100
      times_wltoggle:
        - 35
        - 65
  heiserman:
    test1-L1.xls:
      time_total: 60
      times_wltoggle:
        - 20
        - 45
    test2-L1.xls:
      time_total: 100
      times_wltoggle:
        - 35
        - 65

htm_gridsearch:
  SP=:
    - false
    - true
  HZ=:
    - 6.67
  PERMDEC=:
    - 0.0
#    - 0.025
#    - 0.05
#    - 0.075
    - 0.1
  PADDING%=:
#    - -30
#    - -20
#    - -10
    - 0
#    - 10
#    - 20
#    - 30

features:
  in:
    - steering angle
  pred:
    - steering angle

dirs:
  input: /home/ubuntu/workload_assessor/data  #/Users/samheiserman/Desktop/repos/workload_assessor/data
  output: /home/ubuntu/workload_assessor/results  #/Users/samheiserman/Desktop/repos/workload_assessor/results

colnames:
  - timestamp
  - steering angle
  - brake pressure

columns_model:
  - steering angle

clip_percents:
  start: 0
  end: 0

hzs:
  baseline: 100
  convertto: 6.67  #5

testtypes_filenames:
  training:
    - training1.xls
    - training2.xls
    - training3.xls
    - training4.xls
    - training5.xls
    - training6.xls
    - training7.xls
    - training8.xls
    - training9.xls
    - training10.xls
  Level 0:
    - test7-L0.xls
    - test8-L0.xls
  Level 1:
    - test1-L1.xls
    - test2-L1.xls
  Level 2:
    - test3-L2.xls
    - test4-L2.xls
  Level 3:
    - test5-L3.xls
    - test6-L3.xls

modnames_grids:
  ARIMA:
    p:
      - 1
      - 3
    d:
      - 0
      - 1
    q:
      - 0
      - 1
      - 3
    # trend: 'c' ['', '', '']
  VARIMA:
    p:
      - 1
      # - 3
    d:
      - 0
    q:
      - 0
      # - 3
    # trend: 'c' ['', '', '']
  NBEATSModel:
    # output_chunk_length: int,
    input_chunk_length:
      - 5
    num_stacks:
      - 30
    num_blocks:
      - 1
    num_layers:
      - 4
    layer_widths:
      - 256
    dropout:
      - 0.0
    generic_architecture:
      - True
    expansion_coefficient_dim:
      - 5
    trend_polynomial_degree:
      - 2
    activation:
      - "ReLU"  ## ['ReLU','RReLU', 'PReLU', 'Softplus', 'Tanh', 'SELU', 'LeakyReLU',  'Sigmoid']
  TCNModel:
    # output_chunk_length: int,
    input_chunk_length:
      - 5
    num_filters:
      - 3
    kernel_size:
      - 3
    dilation_base:
      - 2
    weight_norm:
      - False
    dropout:
      - 0.2
    # num_layers: int,
    # dropout_fn,
  TransformerModel:
    # output_chunk_length: int,
    input_chunk_length:
      - 5
    d_model:
      - 64
    nhead:
      - 4
    num_encoder_layers:
      - 3
    num_decoder_layers:
      - 3
    dim_feedforward:
      - 512
    dropout:
      - 0.1
    activation:
      - "relu"  ## ["relu", "gelu"]
    # custom_encoder: Optional[nn.Module] = None,
    # custom_decoder: Optional[nn.Module] = None,
  RNNModel:
    input_chunk_length:
      - 5
    training_length:
      - 5
    model: ## ["RNN", "LSTM", "GRU"]
      - LSTM
    hidden_dim:
      - 25
    n_rnn_layers:
      - 1
    dropout:
      - 0.0
  LightGBMModel:
    lags:
      - 1
      - 5
      - 10
    # lags_past_covariates: Union[int, List[int]] = None,
    # lags_future_covariates: Union[Tuple[int, int], List[int]] = None,
    # output_chunk_length: int = 1,
    # quantiles: List[float] = None,
    # random_state: Optional[int] = None,
    # add_encoders: Optional[dict] = None,
      # = {
      # 'cyclic': {'future': ['month']},
      # 'datetime_attribute': {'future': ['hour', 'dayofweek']},
      # 'position': {'past': ['absolute'], 'future': ['relative']},
      # 'custom': {'past': [lambda idx: (idx.year - 1950) / 50]},
      # 'transformer': Scaler()
      # }
    # likelihood: str = None,
    #   = ['quantile', 'poisson']

htm_config_model:
  models_encoders:
    n: 400
    w: 21
    n_buckets: 130
    p_padding: 10
    seed: 0
  models_params:
    anomaly_likelihood:
      probationaryPeriod: 500
      reestimationPeriod: 100
    sp:
      potentialPct: 0.8
      columnCount: 2048
      globalInhibition: true
      boostStrength: 0.0
      localAreaDensity: 0.0  #0.1
      stimulusThreshold: 0.0
      numActiveColumnsPerInhArea: 40  #0
      synPermActiveInc: 0.003
      synPermConnected: 0.2
      synPermInactiveDec: 0.0005
      wrapAround: true
      minPctOverlapDutyCycle: 0.001
      dutyCyclePeriod: 1000
      seed: 0  #1956
    tm:
      activationThreshold: 20
      cellsPerColumn: 32
      columnDimensions: 2048
      initialPerm: 0.21  #0.24
      maxSegmentsPerCell: 128
      maxSynapsesPerSegment: 128
      minThreshold: 13
      newSynapseCount: 31
      permanenceDec: 0.0  #0.008
      permanenceInc: 0.10  #0.04
      permanenceConnected: 0.5
      predictedSegmentDecrement: 0.001
      seed: 0  #1960
  models_predictor:
    enable: false
    resolution: 1
    sdrc_alpha: 0.1
    steps_ahead:
    - 1
    - 2
  spatial_anomaly:
    enable: false  #true
    tolerance: 0.05
    perc_min: 0
    perc_max: 100
    anom_prop: 0.3
    window: 100000

htm_config_user:
  features:
    steering angle:
      type: float
      min: null
      max: null
      weight: 1.0
  models_state:
    model_for_each_feature: false
    return_pred_count: true
    use_sp: true
  timesteps_stop:
    learning:  #100000
    running:  #110000
    sampling:  #10000

subjects_wllevels_tlx:
  zaychik:
    Level 0: 0.1
    Level 1: 1.1
    Level 2: 2.1
    Level 3: 3.1
  rian:
    Level 0: 0.2
    Level 1: 1.2
    Level 2: 2.2
    Level 3: 3.2
  miller:
    Level 0: 1.3
    Level 1: 2.3
    Level 2: 3.3
    Level 3: 3.3
  jeremy:
    Level 0: 0.4
    Level 1: 1.4
    Level 2: 2.4
    Level 3: 3.4
  jacob:
    Level 0: 0.5
    Level 1: 1.5
    Level 2: 2.5
    Level 3: 3.5
  mike:
    Level 0: 0.5
    Level 1: 1.5
    Level 2: 2.5
    Level 3: 3.5
  hiroki:
    Level 0: 0.6
    Level 1: 1.6
    Level 2: 2.6
    Level 3: 3.6
  heiserman:
    Level 0: 0.7
    Level 1: 1.7
    Level 2: 2.7
    Level 3: 3.7

train_models: true
data_cap: 100000
eval_metric: rmse
forecast_horizon: 1
test_prop: 0.3
time_col: timestamp
file_type: xls
scale: false
