file_type: xls
colnames:
  - timestep
  - steering angle
  - brake pressure
columns_model:
  - steering angle
hzs:
  baseline: 100
  convertto: 15
clip_percents:
  start: 20
  end: 20

dirs:
  input: /Users/samheiserman/Desktop/repos/workload_assessor/data
  output: /Users/samheiserman/Desktop/repos/workload_assessor/results

testtypes_filenames:
  training:
    - training3.xls
    - training4.xls
    - training5.xls
    - training6.xls
    - training7.xls
    - training8.xls
  test_level_0:
    - training9.xls
    - training10.xls
  test_level_1a:
    - level1.xls
  test_level_1b:
    - level2.xls
  test_level_2:
    - level3.xls

htm_config:
  features:
    - steering angle
  models_encoders:
    minmax_percentiles:
      - 1
      - 99
    n: 700
    n_buckets: 140
    sparsity: 0.02
    timestamp:
      enable: false
      feature: satellite_time
      timeOfDay:
        - 30
        - 1
      weekend: 21
  models_params:
    anomaly:
      period: 1000
    predictor:
      sdrc_alpha: 0.1
    sp:
      boostStrength: 2.0
      columnCount: 2048
      localAreaDensity: 0.04395604395604396
      potentialPct: 0.8
      synPermActiveInc: 0.05  #0.003
      synPermConnected: 0.1  #0.2
      synPermInactiveDec: 0.085  #0.0005
    tm:
      activationThreshold: 13
      cellsPerColumn: 32
      initialPerm: 0.21
      maxSegmentsPerCell: 128
      maxSynapsesPerSegment: 32
      minThreshold: 10
      newSynapseCount: 20
      permanenceConnected: 0.3
      permanenceDec: 0.1
      permanenceInc: 0.1
  models_state:
    model_for_each_feature: false
    save_outputs_accumulated: true
    use_sp: false
    track_iter: 10
    track_tm: false
  timesteps_stop:
    learning: 100000
    running: 110000
    sampling: 30